name: Commit lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: setup
      run: |
        npm install -g @commitlint/cli @commitlint/config-conventional
    - name: commitlint
      run: |
        git log --format=%B -n 1 $GITHUB_SHA | commitlint

