name: E2E tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Prepare tests
      run: |
        pip install -U setuptools pip

    - name: E2E tests
      run: |
        export ENVIRONMENT="CI"
        bash .scripts/tests-e2e.sh
